<?php

namespace CodersLabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findByIdGreaterThan($id)
    {
        $query = $this
            ->getEntityManager()
            ->createQuery(
                'SELECT b FROM CodersLabBundle:Book b WHERE b.id > :id'
            )
            ->setParameter('id', $id);

        return $query->getResult();
    }

    public function findByRatingGreaterThan($rating)
    {
        $query = $this
            ->getEntityManager()
            ->createQuery(
                'SELECT b FROM CodersLabBundle:Book b WHERE b.rating > :rating'
            )
            ->setParameter('rating', $rating);

        return $query->getResult();
    }

    public function findByName($name)
    {
        $query = $this
            ->getEntityManager()
            ->createQuery(
                'SELECT b FROM CodersLabBundle:Book b WHERE b.name LIKE :name'
            )
            ->setParameter('name', $name . '%');

        return $query->getResult();
    }
}
